### ISSUE TITLE
marshalparser cannot parse pyc files if not named *.pyc

### ISSUE THREAD

**Issue by hroncok** [fedora-python/marshalparser#3]
I've played with marshalparser a bit and I have trouble using it on files with arbitrary filenames.

```
$ touch foo.py 
$ python3.8 -m foo
$ mv __pycache__/foo.cpython-38.pyc test.dat
$ python -m marshalparser -p test.dat 
Cannot read/parse byte 85 b'U' on possition 0
Might be error or unsupported TYPE
```

Or even:

```
$ touch foo.py 
$ python3.9 -m foo
$ mv __pycache__/foo.cpython-39.pyc test.dat
$ python -m marshalparser -p test.dat 
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File ".../marshalparser/marshalparser/__main__.py", line 3, in <module>
    main()
  File ".../marshalparser/marshalparser/marshalparser.py", line 359, in main
    parser.parse()
  File ".../marshalparser/marshalparser/marshalparser.py", line 50, in parse
    self.read_object()
  File ".../marshalparser/marshalparser/marshalparser.py", line 119, in read_object
    result = self.read_string()
  File ".../marshalparser/marshalparser/marshalparser.py", line 221, in read_string
    bytes = self.read_bytes(size)
  File ".../marshalparser/marshalparser/marshalparser.py", line 208, in read_bytes
    index, byte = next(self.iterator)
StopIteration
```

It seems that marshalparser relies on the filename to skip the pyc header:

https://github.com/fedora-python/marshalparser/blob/668a846de245bdf475042fab5e872149b55fd9e2/marshalparser/marshalparser.py#L35-L41

I find that a tad confusing. I would assume all processed files have the header. Can a non-default `--pure-marshal` or `--no-header` switch be added to handle the cases where the `pyc` header is missing? Or even better, can the header be detected?

**Comment by frenzymadness** [comment]
Honestly, marshalparser supports non-pyc files only because it's much easier to parse a file created manually than a small pyc file so it's good for debugging purposes but with no real use case I can think of.

Is there any real use case behind this issue?

It should be doable to check a pyc header (magic number) first and if it cannot be parsed, consider the file as a non-pyc marshal dump.

**Comment by hroncok** [comment]
> Honestly, marshalparser supports non-pyc files only because it's much easier to parse a file created manually than a small pyc file so it's good for debugging purposes but with no real use case I can think of.

I thought that much. In that case, an explicit `--no-header` switch for debugging makes sense, if the detection proves to be problematic.

> Is there any real use case behind this issue?

I was comparing some pyc files, so I've moved them to `__pycache__/foo.cpython-39.pyc_1` and `__pycache__/foo.cpython-39.pyc_2` . Also, sometimes, you want to use the `<(...)` shell construct.

**Comment by frenzymadness** [comment]
Implementation is not that hard and it seems it works well — #4
